xcopy /s /y  /exclude:exclude_list.txt ".\1. Project\Engine\*.h" ".\3. External\Include\Engine"
xcopy /s /y  /exclude:exclude_list.txt ".\1. Project\Engine\*.fx" ".\2. OutputFile\bin\content\shader"
xcopy /s /y  /exclude:exclude_list.txt ".\1. Project\Client\CSaveLoadMgr.h" ".\3. External\Include\Client"
xcopy /s /y  /exclude:exclude_list.txt ".\1. Project\PhysEngine\*.h" ".\3. External\Include\PhysEngine"
xcopy /s /y  /exclude:exclude_list.txt ".\1. Project\PhysEngine\Export\*.h" ".\3. External\Include\PhysEngine"